name = "echo-community-api"
main = "src/index.js"
compatibility_date = "2026-02-12"

[[d1_databases]]
binding = "DB"
database_name = "echo-main-db"
database_id = "12cb2541-d8d4-48a2-9a69-db6d1348d554"

[vars]
ADMIN_EMAILS = "chen944420634@gmail.com"
GOOGLE_CLIENT_ID = "1043857890282-3u5cd4hj22uv637ofsvmcgjbaptnt0q1.apps.googleusercontent.com"